server: 
  port: 8070 

spring: 
  application: 
    name: eureka-server 
  config:
    import: "optional:configserver:http://localhost:8071/"

logging:
  level:
    com:
      demo:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
